name: ProjecteDispositius
description: A new Flutter project.

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cloud_firestore: ^0.14.3+1
  cupertino_icons: ^1.0.0
  firebase_auth: ^0.18.3+1
  http: ^0.12.0+2
  omdb_dart: ^0.0.2
  path_provider: ^1.6.22

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/background.gif
  fonts:
    - family: LemonMilk
      fonts:
        - asset: fonts/LEMONMILK-Light.otf
        - asset: fonts/LEMONMILK-LightItalic.otf
          style: italic
